In [58]:
# 4
import numpy as np
X=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)

X=X/np.amax(X,axis=0)
y=y/100

def sigmoid(x):
    return 1/(1+np.exp(-x))
def derivatives_sigmoid(x):
    return x*(1-x)

epoch=5000
lr=0.1

inputlayer_neurons=2
hiddenlayer_neurons=3
output_neurons=1

wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):
    hinpl=np.dot(X,wh)+bh
    hlayer_act=sigmoid(hinpl)

    outinpl=np.dot(hlayer_act,wout)+bout
    output=sigmoid(outinpl)

    # till this is enough

    EO=y-output
    outgrad=EO*derivatives_sigmoid(output)

    EH=outgrad.dot(wout.T)
    hiddengrad=EH*derivatives_sigmoid(hlayer_act)

    wout+=hlayer_act.T.dot(outgrad)*lr
    wh+=X.T.dot(hiddengrad)*lr

    # the code above is to improve some accuracy
    
print("Input: \n"+str(X))
print("Actual output: \n"+str(y))
print("Predicted Output: \n",output)

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.96907224]
 [0.96142998]
 [0.96841738]]


In [79]:
# read this
import numpy as np

X=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)

def deri(x):
  return x*(1-x)

def sigmoid(x):
  return 1/(1+np.exp(-x))

X=X/np.amax(X,axis=0)
y=y/100
input_layer = 2
hid_layer = 3
out_layer = 1

wh=np.random.uniform(size=(input_layer,hid_layer))
bh=np.random.uniform(size=(1,hid_layer))
wout=np.random.uniform(size=(hid_layer,out_layer))
bout=np.random.uniform(size=(1,out_layer))

epoch=5000
lr=0.1

for i in range(epoch):
  hidL=np.dot(X,wh)+bh
  hSig=sigmoid(hidL)
  outL=np.dot(hidL,wout)+bout
  oSig=sigmoid(outL)
  
print(X)
print(y)
print(oSig)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.86]
 [0.89]
 [0.9 ]]
[[0.96098671]
 [0.91556577]
 [0.95752535]]
